### ISSUE TITLE
Cannot import RSVP

### ISSUE THREAD

**Issue by lsthornt** [RuslanZavacky/ember-cli-ifa#7]
Hi there, thanks for your great work on this problem!

I took a stab at adding integrating IFA into our app, but ran into an issue where RSVP could not be found to import for the initializer. I haven't dug into the issue enough yet to know if its coming from outdated Ember (1.13.12) or NPM2 nested modules, but I was wondering if there would be a problem importing `Ember` and using `Ember.RSVP` in the case that this is due to a different package layout in Ember 1.13?

**Comment by RuslanZavacky** [comment]
Hey @lsthornt, thank you :) 

Can you please post your package.json / bower.json (or at least some common versions of ember and ember-cli?)

Also, do you https://github.com/ember-cli/ember-cli-shims in your project? 

If you can give me a bit more details, I'll look into it in couple hours and possibly will be able to solve it :) I suspect its because of an Ember version, as I've tested it only with 2+ and there might be some issues with previous ones.

**Comment by lsthornt** [comment]
Relevant bower.json entries:
```
    "ember": "1.13.12",
    "ember-cli-shims": "0.0.6",
    "ember-data": "1.13.15",
    "ember-load-initializers": "0.1.7",
    "ember-resolver": "~0.1.20",
```

Relevant package.json entries:
```
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "^1.13.15",
    "ember-cli-babel": "^5.1.5",
```

It's likely some/most of the more minor libs can be upgraded

**Comment by RuslanZavacky** [comment]
@lsthornt I'll look into it later today :)

**Comment by RuslanZavacky** [comment]
To elaborate on the issue, It seemed like support of 1.13 might be quite a problem. Anyway, It would be a fantastic for everyone, if you can update your app and be on the edge of ember :)

For now, I'll close this issue.
